### ISSUE TITLE
Compile node_modules automatically

### ISSUE THREAD

**Issue by lastmjs** [graphcool/framework#1218] opened 2017-11-09 01:24 UTC
I've been running into issues lately with compiling node modules that have native code. Depending on my local machine's architecture and node version, I might get errors in serverless functions because the environment of the serverless functions is different than my local machines. I think this is something that the framework should take care of itself, either by using docker itself to compile node modules, or somehow when bundled and pushed, the node_modules should be installed in the cloud. There are too many different machines and environments to make the user responsible for this. I've dealt with module version mismatches and ELF issues with bcrypt.

**Comment by kbrandwijk** [comment] 2017-11-09 01:29
Duplicate of https://github.com/graphcool/framework/issues/795

**Closed** 2017-11-09 01:32 UTC
