### ISSUE TITLE
`types` field in graphcool.yml should accept list of strings

### ISSUE THREAD

**Issue by schickling** [graphcool/framework#1311] opened 2017-11-21 11:21 UTC
When working with bigger data models I want the ability to split up my type definitions into multiple files. Therefore the `types` field in graphcool.yml should accept list of strings.

Example:

```yml
types:
- models.graphql
- enums.graphql
```

**Comment by marktani** [comment] 2017-11-21 11:22
Duplicate of #774.

**Closed by marktani** 2017-11-21 11:22 UTC
Labels: component/cli, kind/feature
