### ISSUE TITLE
Mutation creates duplicates always

### ISSUE THREAD

**Issue by state0fmind** [graphcool/framework#1454] opened 2017-12-26 12:27 UTC
**Current behavior**
Mutation creates duplicates always.

**Reproduction**
> Repo - https://github.com/state0fmind/refract

**Expected behavior?**
createpost/create user shouldn't create duplicates.

> duplicate https://github.com/graphql-boilerplates/node-graphql-server/issues/59

**Comment by state0fmind** [comment] 2017-12-26 13:37
> duplicate https://github.com/graphql-boilerplates/node-graphql-server/issues/59

**Comment by marktani** [comment] 2017-12-29 09:40
Closing as duplicate of graphql-boilerplates/node-graphql-server#59.

**Closed by marktani** 2017-12-29 09:40 UTC
