### ISSUE TITLE
Can't test permission queries anywhere

### ISSUE THREAD

**Issue by dukuo** [graphcool/framework#1305] opened 2017-11-20 18:29 UTC
**Current behavior**
Open a Permission Tab from the web console, can't run any `SomeXXXExists` query

**Reproduction**
- Login to the console
- Click Playground
- Click on the Key Icon of the top right corner
- run `query QueryTest($user_ID:ID!){ SomeUserExists(filter:{id:$user_ID}}`
- Get an error stating that there's no such query, and then relating me to _allUsersMeta and stuff.

Please check [this forum post](https://www.graph.cool/forum/t/cant-test-permission-queries-using-permission-tabs-nor-create-them-using-the-consoles-ui/1661) with additional information such as screenshots and logs.

**Expected behavior?**
Should run any `SomeXXXXExists` with no problem from the special permissions tab of the web console.

**Comment by kbrandwijk** [comment] 2017-11-21 01:20
The same thing applies to the permissions endpoint (https://api.graph.cool/simple/v1/c......./permissions)

**Comment by kbrandwijk** [comment] 2017-11-21 17:55
I no longer run into this issue all of a sudden, so I assume there was a fix?

**Comment by marktani** [comment] 2017-11-21 17:56
My understanding is that the issue described in the OP is still reproducible (at least for some versions/machines). I was not able to reproduce problems you reported about `https://api.graph.cool/simple/v1/c......./permissions` directly.

**Comment by kbrandwijk** [comment] 2017-11-21 17:57
My issue was exactly the same as described [here](https://www.graph.cool/forum/t/cant-test-permission-queries-using-permission-tabs-nor-create-them-using-the-consoles-ui/1661), but on the permissions endpoint directly. That seems fixed now.

**Comment by dukuo** [comment] 2017-11-21 17:58
No, the issue is now fixed, don't know which commit was though, but it seems that all `SomeXXXExists` queries are accesible through either the Playground or simpleApi/permissions with Bearer platformToken in the Authorization header field.

**Comment by kbrandwijk** [comment] 2017-11-21 17:58
Well, I'm still getting this issue in the console...

**Comment by dukuo** [comment] 2017-11-21 18:03
Are you getting any useful logs @kbrandwijk ? I tried in different browsers and projects and it's fixed for me I think.

**Comment by kbrandwijk** [comment] 2017-11-21 18:09
![image](https://user-images.githubusercontent.com/852069/33088912-56bd2cae-ceef-11e7-9500-b19c76c0481e.png)

Windows 10 Pro 17025.rs_prerelease.171020-1626
Chrome Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by marktani** [comment] 2017-11-21 18:10
Thanks, we're looking into a fix for that particular error soon. I'll revisit this issue after a fix is out 🙂

**Comment by dukuo** [comment] 2017-11-21 18:10
well even though I can access all permission queries, i'm still getting that same error so I don't think it has to do with the issue .

**Comment by dukuo** [comment] 2017-11-30 17:45
UPDATE: It's no longer a bug, don't know which commit was the fix though.

**Comment by kbrandwijk** [comment] 2017-11-30 18:49
@dukuo It's working now, apart from the slight inconsistency that the permission query tab shows no headers, even though it is using an Authorization header. If I connect to the `/permissions` endpoint playground directly, I also need to add that header.
![image](https://user-images.githubusercontent.com/852069/33448889-7c1d8f4c-d607-11e7-8791-c0bf54c57b72.png)

**Comment by marktani** [comment] 2017-12-04 09:28
The latest playground version does not show the permission tab anymore, as it had a couple of problems. Please see instructions to work with the permissions endpoint directly [here](https://www.graph.cool/forum/t/testing-permission-queries/1661/12?u=nilan).

**Closed by marktani** 2017-12-04 09:28 UTC
Labels: component/console, component/playground, kind/bug
