### ISSUE TITLE
Feature request: `graphcool deploy` without updating functions

### ISSUE THREAD

**Issue by heymartinadams** [graphcool/framework#1246] opened 2017-11-10 21:54 UTC
**What feature are you missing?**
Proposal to update `graphcool deploy` to deploy changes to the `Types` and `Permissions` without updating `Functions` if functions haven’t changed.

**How could this feature look like in detail? Tradeoffs?**
Currently, with 8 functions in my app, it takes 92.3 seconds 😱 to update the functions on a single `graphcool deploy`—even if none have been changed or updated. That may seem like a small, one-time lag, but during times when code is updated in quick, successive iterations, it can add quite a lag.

**Comment by marktani** [comment] 2017-11-10 21:59
Two notes:

* this is a duplicate of #975
* it seems like you are storing the Graphcool service definition in the same directory as your frontend application. `graphcool deploy` picks up `node_modules`, bundles it, zips it + uploads it. Please follow a folder structure similar to the one used here: https://github.com/graphcool-examples/react-graphql/tree/master/authentication-with-email-and-apollo. That is, a separate folder for the service definition (might be called `backend`, `server`, `api`, `graphcool`, ... 😄).

**Closed by marktani** 2017-11-10 21:59 UTC

**Comment by heymartinadams** [comment] 2017-11-10 23:26
Awesome, thank you @marktani!
