### ISSUE TITLE
Better error message when omitting required type for createdAt/updateAt

### ISSUE THREAD

**Issue by schickling** [graphcool/framework#1161] opened 2017-11-03 23:59 UTC
When adding the `createdAt`/`updatedAt` field to a model and omitting the `!` after the type, the presented error message should be more helpful.

Incorrect:

```graphql
type User @model {
  id: ID! @isUnique
  createdAt: DateTime
}
```

Correct:

```graphql
type User @model {
  id: ID! @isUnique
  createdAt: DateTime! # note the !
}
```

This is the current error message:

![image](https://user-images.githubusercontent.com/1567498/32399991-3475ccd6-c0b8-11e7-9da0-c3f81245616b.png)

**Comment by do4gr** [comment] 2017-11-05 10:05
This is a duplicate of https://github.com/graphcool/framework/issues/926 which will be fixed when 0.9 is deployed.

**Closed by do4gr** 2017-11-05 10:05 UTC
Labels: component/framework/server, theme/error-messages
