### ISSUE TITLE
IP address may not be localhost

### ISSUE THREAD

**Issue by AlexanderChen1989** [graphcool/framework#1220] opened 2017-11-09 02:14 UTC
https://github.com/graphcool/framework/blob/dee6648841d264c1ddeddc7ccbb408d02e1d6e40/cli/packages/graphcool-cli-engine/src/Environment.ts#L679

**Comment by kbrandwijk** [comment] 2017-11-09 02:32
Duplicate of https://github.com/graphcool/framework/issues/1092

**Closed** 2017-11-09 09:20 UTC
Labels: component/cli, kind/bug
