### ISSUE TITLE
`gc deploy --force --dry-run` deploys for real

### ISSUE THREAD

**Issue by marktani** [graphcool/framework#973] opened 2017-10-21 15:15 UTC
![image](https://user-images.githubusercontent.com/1780597/31853085-7515f8f4-b683-11e7-9f0b-4e06a9295159.png)

**Comment by kbrandwijk** [comment] 2017-10-29 04:25
Nope, `-d` == 'default', `-D` == 'dry-run'. Confirmed that using `gc -Df` actually does a dry-run...

**Comment by kbrandwijk** [comment] 2017-11-02 00:38
@marktani close?

**Comment by marktani** [comment] 2017-11-02 07:59
it's still misleading, maybe switch `-D` and `-d`?

**Comment by timsuchanek** [comment] 2017-11-03 16:56
I switched `-d` and `-D`, it will be released in `0.9`.

**Comment by kbrandwijk** [comment] 2017-11-03 17:28
Make sure that you make that change very clear! Because I know a lot of people use scripts, and you have now changed their dry-run script to actually deploy to the default environment, which I think is not optimal!

**Closed** 2017-11-06 08:59 UTC
Labels: component/cli, kind/bug
