### ISSUE TITLE
Using a GraphQL alias on mutations gives Permission Error if type has a Permission Query for READ

### ISSUE THREAD

**Issue by schickling** [graphcool/framework#395] opened 2017-09-08 09:29 UTC
<a href="https://github.com/adrianocola"><img src="https://avatars3.githubusercontent.com/u/1678020?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [adrianocola](https://github.com/adrianocola)**
_Thursday Jun 29, 2017 at 15:15 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/156_

----

**What is the current behavior?**
Labeling a delete mutation gives an error if the deleted Type have a read permission query. The item is deleted, but the server returns a permission error.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

Given this schema:
```graphql
type Test implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  name: String!
  updatedAt: DateTime!
}
```

This EVERYONE READ permission query:
```graphql
query ($node_id: ID!) {
  SomeTestExists(
    filter: {
      id: $node_id
    }
  )
}
```

**If applicable, share the query, mutation or subscription for reproduction**

Create some data:
```graphql
mutation{
  createTest(name: "test"){
    id # USE THIS ID!
  }
}
```

Try to delete (**run query as `EVERYONE`**):
```graphql
mutation{
  someLabel: deleteTest(id: "<PREV_ID>"){
    id
  }
}
```

Error:
```graphql
{
  "data": {
    "someLabel": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "someLabel",
        "id"
      ],
      "code": 3008,
      "message": "Insufficient Permissions",
      "requestId": "cj4ikit1y0usr0153erl6p5fr"
    }
  ]
}
```

If I remove the label or the READ permission query, everything works fine.

**What is the expected behavior?**
Not return a permission error!

**Comment by schickling** [comment] 2017-09-08 09:29
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Thursday Jun 29, 2017 at 15:30 GMT_

----

Thanks for the detailed report! I can reproduce this and it also at least affects create mutations as well.

**Comment by sorenbs** [comment] 2017-09-08 21:07
The issue is that there is an implicit read permission on fields in the payload of a mutation that were provided as arguments to the payload. This mechanism relies on the field names and does not take aliases into account.

Thanks for reporting this!

**Comment by marktani** [comment] 2017-11-08 15:03
This is now fixed :tada:

**Closed by marktani** 2017-11-08 15:03 UTC
Labels: area/permissions, component/framework/api, kind/bug
